---
driver:
  associate_public_ip: true
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  iam_profile_name: <%= ENV['AWS_DEFAULT_IAM_ROLE'] %>
  instance_type: t2.micro
  name: ec2
  region: <%= ENV['AWS_REGION'] %>
  require_chef_omnibus: true
  security_group_ids: [ <%= ENV['AWS_DEFAULT_SECURITY_GROUP'] %> ]
  subnet_id: <%= ENV['AWS_DEFAULT_SUBNET'] %>
  tags:
    Name: test-kitchen-amazon

transport:
 ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
 username: ec2-user

provisioner:
  name: chef_zero

platforms:
  - name: amazon-linux
    driver:
      image_id: ami-6869aa05

suites:
  - name: default
    run_list:
      - recipe[s3encrypt::test1]
    attributes:
      s3encrypt:
        encryption_context: "SingleStone"
        s3_bucket: "singlestone"
        s3_secret_path: "temp/secrets.json"
